name: Frontend/ Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Angular App
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      
      # .github/workflows/frontend.yml  (your Static Web Apps workflow)
      - name: Run Tests with Coverage
        run: |
          cd frontend
          npx ng test --watch=false --browsers=ChromeHeadlessCI --code-coverage

      # Always run the upload step, even if tests fail, so you can see missing-file errors.
      - name: Upload frontend coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: ./frontend/coverage/lcov.info   # 👈 full path from repo root
          flags: frontend
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      # Optional: debug if it still fails
      - name: Debug coverage tree
        if: always()
        run: ls -R frontend/coverage || true



      - name: Build Angular App
        run: |
          cd frontend
          npx ng build --configuration=production

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with: 
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_MUSHROOM_00C4CE01E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: frontend/dist/frontend/browser
          skip_app_build: true
          api_location: ""
          data_api_location: ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_MUSHROOM_00C4CE01E }}
          action: close





