name: Backend/ Build and deploy Node.js app to Azure Web App - vows-n-veils

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      # Backend
      - name: Install backend dependencies and build
        run: |
          cd backend
          npm install
          npm run build --if-present

      - name: Run backend tests with coverage
        run: |
          cd backend
          npm test -- --coverage
        continue-on-error: true
        
      - name: Upload backend coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: ./backend/coverage/lcov.info
          flags: backend
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      # Frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend tests with coverage
        run: |
          cd frontend
          npx ng test --watch=false --browsers=ChromeHeadlessCI --code-coverage
        continue-on-error: true

      - name: Upload frontend coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: ./frontend/coverage/lcov.info
          flags: frontend
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      # Upload artifact for deployment
      - name: Upload backend artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./artifact

      - name: List contents (for debugging)
        run: ls -la ./artifact

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vows-n-veils'
          slot-name: 'Production'
          package: ./artifact
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6A566639885F4EC0BE516E1D82B9F385 }}